# DỮ LIỆU TỪ VỰNG HSK 2 (CẤU TRÚC GỌN NHẸ)
# File này chỉ dùng để nạp vào Database lần đầu tiên.

HSK_DATA = [
    {"Hán tự": "吧", "Pinyin": "ba", "Nghĩa": "nhé, nhỉ (trợ từ)"},
    {"Hán tự": "白", "Pinyin": "bái", "Nghĩa": "trắng"},
    {"Hán tự": "百", "Pinyin": "bǎi", "Nghĩa": "trăm"},
    {"Hán tự": "帮助", "Pinyin": "bāngzhù", "Nghĩa": "giúp đỡ"},
    {"Hán tự": "报纸", "Pinyin": "bàozhǐ", "Nghĩa": "báo chí"},
    {"Hán tự": "比", "Pinyin": "bǐ", "Nghĩa": "so với"},
    {"Hán tự": "别", "Pinyin": "bié", "Nghĩa": "đừng"},
    {"Hán tự": "宾馆", "Pinyin": "bīnguǎn", "Nghĩa": "khách sạn"},
    {"Hán tự": "长", "Pinyin": "cháng", "Nghĩa": "dài"},
    {"Hán tự": "唱歌", "Pinyin": "chàng gē", "Nghĩa": "hát"},
    {"Hán tự": "出", "Pinyin": "chū", "Nghĩa": "ra"},
    {"Hán tự": "穿", "Pinyin": "chuān", "Nghĩa": "mặc"},
    {"Hán tự": "次", "Pinyin": "cì", "Nghĩa": "lần"},
    {"Hán tự": "从", "Pinyin": "cóng", "Nghĩa": "từ"},
    {"Hán tự": "错", "Pinyin": "cuò", "Nghĩa": "sai"},
    {"Hán tự": "打篮球", "Pinyin": "dǎ lánqiú", "Nghĩa": "chơi bóng rổ"},
    {"Hán tự": "大家", "Pinyin": "dàjiā", "Nghĩa": "mọi người"},
    {"Hán tự": "但是", "Pinyin": "dànshì", "Nghĩa": "nhưng"},
    {"Hán tự": "到", "Pinyin": "dào", "Nghĩa": "đến"},
    {"Hán tự": "得", "Pinyin": "de", "Nghĩa": "trợ từ kết cấu"},
    {"Hán tự": "等", "Pinyin": "děng", "Nghĩa": "đợi"},
    {"Hán tự": "弟弟", "Pinyin": "dìdi", "Nghĩa": "em trai"},
    {"Hán tự": "第一", "Pinyin": "dì yī", "Nghĩa": "thứ nhất"},
    {"Hán tự": "懂", "Pinyin": "dǒng", "Nghĩa": "hiểu"},
    {"Hán tự": "对", "Pinyin": "duì", "Nghĩa": "đúng / đối với"},
    {"Hán tự": "房间", "Pinyin": "fángjiān", "Nghĩa": "phòng"},
    {"Hán tự": "非常", "Pinyin": "fēicháng", "Nghĩa": "vô cùng"},
    {"Hán tự": "服务员", "Pinyin": "fúwùyuán", "Nghĩa": "nhân viên phục vụ"},
    {"Hán tự": "高", "Pinyin": "gāo", "Nghĩa": "cao"},
    {"Hán tự": "告诉", "Pinyin": "gàosu", "Nghĩa": "nói cho biết"},
    {"Hán tự": "哥哥", "Pinyin": "gēge", "Nghĩa": "anh trai"},
    {"Hán tự": "给", "Pinyin": "gěi", "Nghĩa": "cho"},
    {"Hán tự": "公共汽车", "Pinyin": "gōnggòng qìchē", "Nghĩa": "xe buýt"},
    {"Hán tự": "公司", "Pinyin": "gōngsī", "Nghĩa": "công ty"},
    {"Hán tự": "贵", "Pinyin": "guì", "Nghĩa": "đắt"},
    {"Hán tự": "还", "Pinyin": "hái", "Nghĩa": "còn, vẫn"},
    {"Hán tự": "孩子", "Pinyin": "háizi", "Nghĩa": "trẻ con"},
    {"Hán tự": "好吃", "Pinyin": "hǎochī", "Nghĩa": "ngon"},
    {"Hán tự": "黑", "Pinyin": "hēi", "Nghĩa": "đen"},
    {"Hán tự": "红", "Pinyin": "hóng", "Nghĩa": "đỏ"},
    {"Hán tự": "火车站", "Pinyin": "huǒchēzhàn", "Nghĩa": "ga tàu hỏa"},
    {"Hán tự": "机场", "Pinyin": "jīchǎng", "Nghĩa": "sân bay"},
    {"Hán tự": "鸡蛋", "Pinyin": "jīdàn", "Nghĩa": "trứng gà"},
    {"Hán tự": "件", "Pinyin": "jiàn", "Nghĩa": "chiếc, cái (lượng từ)"},
    {"Hán tự": "觉得", "Pinyin": "juéde", "Nghĩa": "cảm thấy"},
    {"Hán tự": "教室", "Pinyin": "jiàoshì", "Nghĩa": "lớp học"},
    {"Hán tự": "姐姐", "Pinyin": "jiějie", "Nghĩa": "chị gái"},
    {"Hán tự": "介绍", "Pinyin": "jièshào", "Nghĩa": "giới thiệu"},
    {"Hán tự": "进", "Pinyin": "jìn", "Nghĩa": "vào"},
    {"Hán tự": "近", "Pinyin": "jìn", "Nghĩa": "gần"},
    {"Hán tự": "就", "Pinyin": "jiù", "Nghĩa": "thì, ngay"},
    {"Hán tự": "咖啡", "Pinyin": "kāfēi", "Nghĩa": "cà phê"},
    {"Hán tự": "开始", "Pinyin": "kāishǐ", "Nghĩa": "bắt đầu"},
    {"Hán tự": "考试", "Pinyin": "kǎoshì", "Nghĩa": "thi cử"},
    {"Hán tự": "可能", "Pinyin": "kěnéng", "Nghĩa": "có thể"},
    {"Hán tự": "可以", "Pinyin": "kěyǐ", "Nghĩa": "có thể / được"},
    {"Hán tự": "课", "Pinyin": "kè", "Nghĩa": "bài học"},
    {"Hán tự": "快", "Pinyin": "kuài", "Nghĩa": "nhanh"},
    {"Hán tự": "快乐", "Pinyin": "kuàilè", "Nghĩa": "vui vẻ"},
    {"Hán tự": "离", "Pinyin": "lí", "Nghĩa": "cách"},
    {"Hán tự": "两", "Pinyin": "liǎng", "Nghĩa": "hai"},
    {"Hán tự": "零", "Pinyin": "líng", "Nghĩa": "số 0"},
    {"Hán tự": "路", "Pinyin": "lù", "Nghĩa": "đường"},
    {"Hán tự": "旅游", "Pinyin": "lǚyóu", "Nghĩa": "du lịch"},
    {"Hán tự": "慢", "Pinyin": "màn", "Nghĩa": "chậm"},
    {"Hán tự": "忙", "Pinyin": "máng", "Nghĩa": "bận"},
    {"Hán tự": "每", "Pinyin": "měi", "Nghĩa": "mỗi"},
    {"Hán tự": "妹妹", "Pinyin": "mèimei", "Nghĩa": "em gái"},
    {"Hán tự": "门", "Pinyin": "mén", "Nghĩa": "cửa"},
    {"Hán tự": "面条", "Pinyin": "miàntiáo", "Nghĩa": "mì"},
    {"Hán tự": "男", "Pinyin": "nán", "Nghĩa": "nam"},
    {"Hán tự": "牛奶", "Pinyin": "niúnǎi", "Nghĩa": "sữa bò"},
    {"Hán tự": "女", "Pinyin": "nǚ", "Nghĩa": "nữ"},
    {"Hán tự": "旁边", "Pinyin": "pángbiān", "Nghĩa": "bên cạnh"},
    {"Hán tự": "跑步", "Pinyin": "pǎo bù", "Nghĩa": "chạy bộ"},
    {"Hán tự": "便宜", "Pinyin": "piányi", "Nghĩa": "rẻ"},
    {"Hán tự": "票", "Pinyin": "piào", "Nghĩa": "vé"},
    {"Hán tự": "妻子", "Pinyin": "qīzi", "Nghĩa": "vợ"},
    {"Hán tự": "起床", "Pinyin": "qǐ chuáng", "Nghĩa": "thức dậy"},
    {"Hán tự": "千", "Pinyin": "qiān", "Nghĩa": "nghìn"},
    {"Hán tự": "铅笔", "Pinyin": "qiānbǐ", "Nghĩa": "bút chì"},
    {"Hán tự": "晴", "Pinyin": "qíng", "Nghĩa": "nắng"},
    {"Hán tự": "去年", "Pinyin": "qùnián", "Nghĩa": "năm ngoái"},
    {"Hán tự": "让", "Pinyin": "ràng", "Nghĩa": "nhường / bảo"},
    {"Hán tự": "日", "Pinyin": "rì", "Nghĩa": "ngày"},
    {"Hán tự": "上班", "Pinyin": "shàng bān", "Nghĩa": "đi làm"},
    {"Hán tự": "身体", "Pinyin": "shēntǐ", "Nghĩa": "cơ thể / sức khỏe"},
    {"Hán tự": "生病", "Pinyin": "shēng bìng", "Nghĩa": "bị ốm"},
    {"Hán tự": "生日", "Pinyin": "shēngrì", "Nghĩa": "sinh nhật"},
    {"Hán tự": "时间", "Pinyin": "shíjiān", "Nghĩa": "thời gian"},
    {"Hán tự": "事情", "Pinyin": "shìqing", "Nghĩa": "sự việc"},
    {"Hán tự": "手表", "Pinyin": "shǒubiǎo", "Nghĩa": "đồng hồ đeo tay"},
    {"Hán tự": "手机", "Pinyin": "shǒujī", "Nghĩa": "điện thoại"},
    {"Hán tự": "说话", "Pinyin": "shuō huà", "Nghĩa": "nói chuyện"},
    {"Hán tự": "送", "Pinyin": "sòng", "Nghĩa": "tặng / tiễn"},
    {"Hán tự": "虽然", "Pinyin": "suīrán", "Nghĩa": "mặc dù"},
    {"Hán tự": "所以", "Pinyin": "suǒyǐ", "Nghĩa": "cho nên"},
    {"Hán tự": "它", "Pinyin": "tā", "Nghĩa": "nó"},
    {"Hán tự": "踢足球", "Pinyin": "tī zúqiú", "Nghĩa": "đá bóng"},
    {"Hán tự": "题", "Pinyin": "tí", "Nghĩa": "đề bài"},
    {"Hán tự": "跳舞", "Pinyin": "tiào wǔ", "Nghĩa": "khiêu vũ"},
    {"Hán tự": "外", "Pinyin": "wài", "Nghĩa": "ngoài"},
    {"Hán tự": "完", "Pinyin": "wán", "Nghĩa": "xong"},
    {"Hán tự": "玩儿", "Pinyin": "wánr", "Nghĩa": "chơi"},
    {"Hán tự": "晚上", "Pinyin": "wǎnshang", "Nghĩa": "buổi tối"},
    {"Hán tự": "往", "Pinyin": "wǎng", "Nghĩa": "về phía"},
    {"Hán tự": "为什么", "Pinyin": "wèi shénme", "Nghĩa": "tại sao"},
    {"Hán tự": "问", "Pinyin": "wèn", "Nghĩa": "hỏi"},
    {"Hán tự": "问题", "Pinyin": "wèntí", "Nghĩa": "vấn đề"},
    {"Hán tự": "西瓜", "Pinyin": "xīguā", "Nghĩa": "dưa hấu"},
    {"Hán tự": "希望", "Pinyin": "xīwàng", "Nghĩa": "hy vọng"},
    {"Hán tự": "洗", "Pinyin": "xǐ", "Nghĩa": "giặt / rửa"},
    {"Hán tự": "小时", "Pinyin": "xiǎoshí", "Nghĩa": "giờ"},
    {"Hán tự": "笑", "Pinyin": "xiào", "Nghĩa": "cười"},
    {"Hán tự": "新", "Pinyin": "xīn", "Nghĩa": "mới"},
    {"Hán tự": "姓", "Pinyin": "xìng", "Nghĩa": "họ"},
    {"Hán tự": "休息", "Pinyin": "xiūxi", "Nghĩa": "nghỉ ngơi"},
    {"Hán tự": "雪", "Pinyin": "xuě", "Nghĩa": "tuyết"},
    {"Hán tự": "颜色", "Pinyin": "yánsè", "Nghĩa": "màu sắc"},
    {"Hán tự": "眼睛", "Pinyin": "yǎnjing", "Nghĩa": "mắt"},
    {"Hán tự": "羊肉", "Pinyin": "yángròu", "Nghĩa": "thịt cừu/dê"},
    {"Hán tự": "药", "Pinyin": "yào", "Nghĩa": "thuốc"},
    {"Hán tự": "要", "Pinyin": "yào", "Nghĩa": "muốn / cần"},
    {"Hán tự": "也", "Pinyin": "yě", "Nghĩa": "cũng"},
    {"Hán tự": "一下", "Pinyin": "yíxià", "Nghĩa": "một chút"},
    {"Hán tự": "已经", "Pinyin": "yǐjīng", "Nghĩa": "đã"},
    {"Hán tự": "一起", "Pinyin": "yìqǐ", "Nghĩa": "cùng nhau"},
    {"Hán tự": "意思", "Pinyin": "yìsi", "Nghĩa": "ý nghĩa"},
    {"Hán tự": "因为", "Pinyin": "yīnwèi", "Nghĩa": "bởi vì"},
    {"Hán tự": "阴", "Pinyin": "yīn", "Nghĩa": "âm u"},
    {"Hán tự": "游泳", "Pinyin": "yóu yǒng", "Nghĩa": "bơi"},
    {"Hán tự": "右边", "Pinyin": "yòubian", "Nghĩa": "bên phải"},
    {"Hán tự": "鱼", "Pinyin": "yú", "Nghĩa": "cá"},
    {"Hán tự": "远", "Pinyin": "yuǎn", "Nghĩa": "xa"},
    {"Hán tự": "运动", "Pinyin": "yùndòng", "Nghĩa": "vận động"},
    {"Hán tự": "再", "Pinyin": "zài", "Nghĩa": "lại"},
    {"Hán tự": "早上", "Pinyin": "zǎoshang", "Nghĩa": "buổi sáng"},
    {"Hán tự": "丈夫", "Pinyin": "zhàngfu", "Nghĩa": "chồng"},
    {"Hán tự": "找", "Pinyin": "zhǎo", "Nghĩa": "tìm"},
    {"Hán tự": "着", "Pinyin": "zhe", "Nghĩa": "đang/trợ từ"},
    {"Hán tự": "真", "Pinyin": "zhēn", "Nghĩa": "thật"},
    {"Hán tự": "正在", "Pinyin": "zhèngzài", "Nghĩa": "đang"},
    {"Hán tự": "知道", "Pinyin": "zhīdào", "Nghĩa": "biết"},
    {"Hán tự": "准备", "Pinyin": "zhǔnbèi", "Nghĩa": "chuẩn bị"},
    {"Hán tự": "走", "Pinyin": "zǒu", "Nghĩa": "đi"},
    {"Hán tự": "最", "Pinyin": "zuì", "Nghĩa": "nhất"},
    {"Hán tự": "左边", "Pinyin": "zuǒbian", "Nghĩa": "bên trái"}
]

